blog/urls.py
from django.urls import path
from . import views

# app_name = "hold"
urlpatterns = [
    path('', views.index, name = 'blog'),
    path('<int:id>', views.PostDetail, name = 'detailPost'),
]

dangnhap/urls.py
from django.urls import path
from .views import logindemo

urlpatterns = [
    path('', logindemo.as_view(), name = 'login'),
]

luachon/urls.py
from django.urls import path
from . import views

app_name = "luachon"
urlpatterns = [
    path('', views.index, name = 'index'),
    path('detail/<int:question_id>', views.detail, name = "detail"),
    path('list/', views.xemds_question, name = 'list'),
    path('<int:question_id>', views.vote, name= "vote"),
]

myweb/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('dangnhap/', include('dangnhap.urls')),
    path('admin/', admin.site.urls),
    path('', include('luachon.urls')),
    path('blog/',include('blog.urls')),
]

blog/models.py
from datetime import datetime
from django.db import models
from django.utils import timezone


class Postform(models.Model):
    title = models.CharField(max_length= 100, null= False)
    content = models.TextField()
    creat_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
    
    # def was_published_recently(self):
        return self.creat_at >= timezone.now() - datetime.timedelta(days = 1)

dangnhap/models.py
from django.db import models

# Create your models here.
class login(models.Model):
    username = models.CharField(max_length=45, null=False)
    email = models.EmailField()
    password = models.CharField(max_length= 50, null = False)
    
    def __str__(self):
        return str(self.email)

luachon/models.py
from django.db import models
from django.db.models.deletion import CASCADE
import datetime
from django.utils import timezone

#lớp question kế thừa từ models
class Question(models.Model):

    question_text = models.CharField(max_length= 200)
    time_public = models.DateTimeField()
    def __str__(self):
        return self.question_text #thuận tiện cho việc xử lí ngôn ngữ

    def was_published_recently(self):
        return self.time_public >= timezone.now() - datetime.timedelta(days=1)

    

class choice(models.Model):
    #liên kết khóa ngoại đến lớp question
    question = models.ForeignKey(Question, on_delete= models.CASCADE)  # khi trl bị xóa đi thì câu hỏi cx bị xóa đi 
    choice_text = models.CharField(max_length= 100)
    vote = models.IntegerField(default= 0)
    def __str__(self):
        return self.choice_text

dangnhap/forms.py
from django import forms
from django.db.models import fields
from .models import login

class login_form(forms.ModelForm):
    class Meta:
        model = login
        fields = ['username', 'password', 'email']

blog/views.py
from django import views
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse, request
from .models import Postform


def index(request):
    pf = Postform.objects.all()
    return render(request, "blog/blog.html", {'pf': pf})

def PostDetail(request, id):
    pd = Postform.objects.get(id = id)
    return render(request, "blog/detail_blog.html", {'pd': pd})

dangnhap/views.py
from django import views
from django.shortcuts import render
from django.views.generic.base import View
from .forms import login_form
from django.http import HttpResponse
from django.views import View


# Create your views here.
class logindemo(View):
    
    def get(self,request):
        f = login_form
        return render(request, 'dangnhap/dangnhap.html', {'f': f})
    
    def post(self,request):
        f = login_form(request.POST)
        if not f.is_valid():
            return HttpResponse("ban nhap sai du lieu roi")
        else:
            f.save()
            return render(request, 'dangnhap/ketqua.html')

luachon/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from .models import Question

def index(request):
    return render(request, 'luachon/base.html')

def xemds_question(request):
    lst = Question.objects.all()
    context = {"ds_quest": lst}
    return render(request, "luachon/questionlist.html", context)

def detail(request, question_id):
    q = Question.objects.get(pk = question_id)
    return render(request, "luachon/detail_question.html", {'qs': q})

def vote(request, question_id):
    #return HttpResponse("You're voting on question %s." % question_id)    
    q = Question.objects.get(pk = question_id)
    try:
        dulieu = request.POST["dvc"]
        c = q.choice_set.get(pk = dulieu)
    except:
        HttpResponse("lỗi không có choice !!!")
    c.vote = c.vote + 1
    c.save()
    return render(request, "luachon/result.html", { "q": q })

blog/templates/blog/blog.html
{% extends "luachon/base.html" %}
{% block content1 %}
    <p>blog list</p>
    {% for item in pf %}
        <p><a href="{% url 'detailPost' item.id %}">{{item.title}}</a></p>
    {%  endfor %}
{% endblock %}

blog/templates/blog/detail_blog.html
{% extends "luachon/base.html" %}
{% block content1 %}
    <h1>{{ pd.title }} </h1>
    <p>{{ pd.content }}</p>
{% endblock %}

dangnhap/templates/dangnhap/dangnhap.html
{% extends "luachon/base.html" %}

{% block content1 %}

    <div>
        <form action="" method="POST">
            {% csrf_token %}
            {{ f.as_p }} 
            <!-- trải ngang f ra-->
            <input type="submit" value="add">
        </form>
    </div> 
    
{% endblock content1 %}

dangnhap/templates/dangnhap/ketqua.html
{% extends "luachon/base.html" %}
{% block content1 %}   
    <h1>bạn đã đăng nhập thành công</h1>
{% endblock content1 %}

luachon/templates/luachon/base.html
{% load static %}
<!DOCTYPE>
<html lang = "en">
    <head>
        <meta charset = "UTF-8">
        <title> Title </title>
        <link rel="stylesheet" href="{% static 'luachon/base.css' %}">
    </head>
<!--float: left  để trôi dạt về bên trái theo 1 hàng
-->
    <body>
        <div class = "header">
            <h1> my header </h1>
        </div>
        <div class = "menu" style = "color: ">
            <ul>
                <li> <a href="{% url 'luachon:list' %}" style="color: rgb(35, 201, 43);">danh sách</a> </li>
                <li> <a href="{% url 'luachon:index' %}" style="color: chartreuse;">trang chủ</a> </li>
                <li> <a href="{% url 'login' %}">đăng nhập</a></li>
                <li> <a href="{% url 'blog' %}" style = "color: rgb(35, 201, 43);">Blog</a> </li>
            </ul>
        </div>
        <div class = "noidung">
            {% block content1 %}
            <!--phần giữa này của trang web sẽ thay đổi dựa vào đường dẫn content1-->
            {% endblock %}
        </div>
    </body>
</html>

luachon/templates/luachon/detail_question.html
{% extends "luachon/base.html" %}
{% block content1 %}
    {% if qs %}
    <form action="{% url 'luachon:vote' qs.id %}" method="POST"> <!--khi ấn nút gửi web đưa sang 1 trang khác để lưu dữ liệu-->
        {% csrf_token %}                           <!--bảo mật trong python-->
        
        <P><b>{{ qs.question_text}}</b></P>
        <ul>{% for item in qs.choice_set.all %}
                <input name="dvc" type="radio" value="{{item.id}}">{{item.choice_text }}
            {% endfor %} 
        </ul>
        <p><input type="submit" value="gửi"></p>
    </form>
    {% else %}
        <h3 style= "color :brown"> Không tồn tại câu hỏi !!!</h3>   
    
    {% endif %}
{% endblock %}

luachon/templates/luachon/questionlist.html
{% extends "luachon/base.html" %}
    {% block content1 %}
        {% if ds_quest %}
            <ul>{% for item in ds_quest%}
                    <p><a href="{% url 'luachon:detail' %}">{{ item.question_text }}</a></p>
                {% endfor %} 
            </ul>
        {% else %}
            <h3 style= "color :brown"> Không có dữ liệu nào !!!</h3>   
        
        {% endif %}
    {% endblock %}

luachon/templates/luachon/result.html
{% extends "luachon/base.html" %}

{% block content1 %}   
    {% if q %}
        <h1>{{ q.question_text }}</h1>
        <p>kết quả của cuộc bình chọn là:</p>
        
            {% for item in q.choice_set.all %}
            <p>{{item.choice_text}} : <span style="color: blue;">{{item.vote}}</span> </p>
            {% endfor %}
        <a href="{% url 'luachon:list'%}"><input type="submit" value="vote tiếp"></a>    
    {% endif %}
{% endblock content1 %}